services:
  - type: web
    name: smart-campus-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: smart_campus
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Campus Administrator
