const express=require('express'),crypto=require('crypto'),path=require('path');
const {MongoClient,ObjectId}=require('mongodb');
const app=express(),port=process.env.PORT||3000,uri=process.env.MONGODB_URI;
if(!uri){console.error('MONGODB_URI is required');process.exit(1)}
const client=new MongoClient(uri);let db,users,sessions,complaints,counters;
const cats={ICT:['ICT Services',24],FACILITIES:['Facilities',48],ELECTRICITY:['Electrical Unit',24],WATER:['Works & Maintenance',24],SECURITY:['Campus Security',4],HOSTEL:['Student Affairs',48],ACADEMIC:['Academic Affairs',48],OTHER:['General Services',72]};
app.use(express.json({limit:'3mb'}));app.use(express.static(path.join(__dirname,'public')));
const mail=v=>String(v||'').trim().toLowerCase(),safe=u=>({id:String(u._id),name:u.name,email:u.email,role:u.role,department:u.department||'',schoolName:u.schoolName||'',campusName:u.campusName||'',schoolType:u.schoolType||'',schoolState:u.schoolState||''});
function pw(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function verify(p,v){const [s,h]=String(v||'').split(':');if(!s||!h)return false;const a=crypto.scryptSync(p,s,64),b=Buffer.from(h,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
async function auth(req,res,next){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({message:'Sign in required'});const s=await sessions.findOne({token:h.slice(7),expiresAt:{$gt:new Date()}});if(!s)return res.status(401).json({message:'Session expired'});const u=await users.findOne({_id:s.userId});if(!u)return res.status(401).json({message:'Account not found'});req.user=u;req.session=s;next()}
const role=(...r)=>(req,res,next)=>r.includes(req.user?.role)?next():res.status(403).json({message:'Not permitted'});
async function token(id){const t=crypto.randomBytes(32).toString('hex');await sessions.insertOne({token:t,userId:new ObjectId(id),expiresAt:new Date(Date.now()+604800000)});return t}
async function nextId(){return (await counters.findOneAndUpdate({_id:'complaint'},{$inc:{seq:1}},{upsert:true,returnDocument:'after'})).seq}
const scope=u=>u.role==='ADMIN'&&!u.schoolName?{}:['STAFF','ADMIN'].includes(u.role)?{schoolName:u.schoolName}:{submittedEmail:u.email};
const out=c=>{if(!c)return null;const x={...c};delete x._id;return x};

app.get('/api/health',async(req,res)=>{try{await db.command({ping:1});res.json({ok:true,database:'mongodb'})}catch{res.status(503).json({ok:false})}});
app.post('/api/auth/register',async(req,res)=>{const {name,password,schoolName,campusName,schoolType,schoolState}=req.body,email=mail(req.body.email);if(!name||!email||!password||!schoolName||!campusName)return res.status(400).json({message:'Complete all required fields'});if(password.length<8)return res.status(400).json({message:'Password must be at least 8 characters'});if(await users.findOne({email}))return res.status(409).json({message:'Email already exists'});const u={name,email,passwordHash:pw(password),role:'STUDENT',schoolName,campusName,schoolType:schoolType||'University',schoolState:schoolState||'',createdAt:new Date()};const r=await users.insertOne(u);u._id=r.insertedId;res.status(201).json({...safe(u),token:await token(u._id)})});
app.post('/api/auth/login',async(req,res)=>{const u=await users.findOne({email:mail(req.body.email)});if(!u||!verify(String(req.body.password||''),u.passwordHash))return res.status(401).json({message:'Invalid email or password'});res.json({...safe(u),token:await token(u._id)})});
app.get('/api/auth/me',auth,(req,res)=>res.json(safe(req.user)));
app.post('/api/auth/logout',auth,async(req,res)=>{await sessions.deleteOne({_id:req.session._id});res.json({ok:true})});

app.get('/api/complaints',async(req,res)=>res.json((await complaints.find({}).sort({createdAt:-1}).limit(100).toArray()).map(out)));
app.get('/api/complaints/mine',auth,async(req,res)=>res.json((await complaints.find({submittedEmail:req.user.email}).sort({createdAt:-1}).toArray()).map(out)));
app.get('/api/complaints/:id',async(req,res)=>{const c=await complaints.findOne({id:Number(req.params.id)});c?res.json(out(c)):res.status(404).json({message:'Complaint not found'})});
app.post('/api/complaints',auth,role('STUDENT'),async(req,res)=>{const {title,description,location,mapX,mapY}=req.body,category=cats[req.body.category]?req.body.category:'OTHER';if(!title||!description||!location)return res.status(400).json({message:'Title, description and location are required'});if(mapX==null||mapY==null)return res.status(400).json({message:'Tag the location on the campus map'});const id=await nextId(),now=new Date(),meta=cats[category],c={id,title,description,location,category,priority:req.body.priority||'MEDIUM',status:'SUBMITTED',department:meta[0],assignedTo:'',submittedBy:req.user.name,submittedEmail:req.user.email,schoolName:req.user.schoolName,campusName:req.user.campusName,mapX:Number(mapX),mapY:Number(mapY),mapLabel:req.body.mapLabel||location,evidenceData:req.body.evidenceData||'',comments:[],auditTrail:[{at:now,by:req.user.name,text:'Complaint submitted'}],createdAt:now,updatedAt:now,dueAt:new Date(now.getTime()+meta[1]*3600000),resolvedAt:null,rating:null,feedback:''};await complaints.insertOne(c);res.status(201).json(out(c))});
app.post('/api/complaints/:id/comments',auth,async(req,res)=>{const id=Number(req.params.id),c=await complaints.findOne({id}),text=String(req.body.text||'').trim();if(!c)return res.status(404).json({message:'Complaint not found'});if(!text)return res.status(400).json({message:'Comment required'});const ok=req.user.role==='ADMIN'||(req.user.role==='STAFF'&&req.user.schoolName===c.schoolName)||req.user.email===c.submittedEmail;if(!ok)return res.status(403).json({message:'No access'});await complaints.updateOne({id},{$push:{comments:{at:new Date(),by:req.user.name,text},auditTrail:{at:new Date(),by:req.user.name,text:'Comment added'}},$set:{updatedAt:new Date()}});res.json(out(await complaints.findOne({id})))});
app.get('/api/staff/complaints',auth,role('STAFF','ADMIN'),async(req,res)=>res.json((await complaints.find(scope(req.user)).sort({createdAt:-1}).toArray()).map(out)));
app.put('/api/complaints/:id/status',auth,role('STAFF','ADMIN'),async(req,res)=>{const id=Number(req.params.id),status=String(req.body.status||''),allowed=['SUBMITTED','ASSIGNED','IN_PROGRESS','AWAITING_STUDENT','RESOLVED','CLOSED','REJECTED'];if(!allowed.includes(status))return res.status(400).json({message:'Invalid status'});const c=await complaints.findOne({id,...scope(req.user)});if(!c)return res.status(404).json({message:'Complaint not found'});await complaints.updateOne({id},{$set:{status,updatedAt:new Date(),resolvedAt:['RESOLVED','CLOSED'].includes(status)?new Date():null},$push:{auditTrail:{at:new Date(),by:req.user.name,text:'Status changed to '+status.replaceAll('_',' ')}}});res.json(out(await complaints.findOne({id})))});
app.put('/api/complaints/:id/assignment',auth,role('STAFF','ADMIN'),async(req,res)=>{const id=Number(req.params.id),c=await complaints.findOne({id,...scope(req.user)});if(!c)return res.status(404).json({message:'Complaint not found'});const assignedTo=String(req.body.assignedTo||req.user.name);await complaints.updateOne({id},{$set:{assignedTo,status:c.status==='SUBMITTED'?'ASSIGNED':c.status,updatedAt:new Date()},$push:{auditTrail:{at:new Date(),by:req.user.name,text:'Assigned to '+assignedTo}}});res.json(out(await complaints.findOne({id})))});
app.post('/api/complaints/:id/feedback',auth,role('STUDENT'),async(req,res)=>{const id=Number(req.params.id),c=await complaints.findOne({id,submittedEmail:req.user.email});if(!c)return res.status(404).json({message:'Complaint not found'});await complaints.updateOne({id},{$set:{rating:Math.max(1,Math.min(5,Number(req.body.rating)||5)),feedback:String(req.body.feedback||'')}});res.json(out(await complaints.findOne({id})))});
app.post('/api/complaints/:id/reopen',auth,role('STUDENT'),async(req,res)=>{const id=Number(req.params.id);await complaints.updateOne({id,submittedEmail:req.user.email},{$set:{status:'IN_PROGRESS',resolvedAt:null,updatedAt:new Date()},$push:{auditTrail:{at:new Date(),by:req.user.name,text:'Complaint reopened'}}});res.json(out(await complaints.findOne({id})))});
app.get('/api/dashboard/summary',async(req,res)=>{const all=await complaints.find({},{projection:{status:1,dueAt:1}}).toArray(),resolved=all.filter(x=>['RESOLVED','CLOSED'].includes(x.status)).length,open=all.filter(x=>!['RESOLVED','CLOSED','REJECTED'].includes(x.status)).length,overdue=all.filter(x=>x.dueAt&&new Date(x.dueAt)<new Date()&&!['RESOLVED','CLOSED','REJECTED'].includes(x.status)).length;res.json({total:all.length,resolved,open,overdue,rate:all.length?Math.round(resolved/all.length*100):0})});
app.get('/api/dashboard/analytics',auth,role('ADMIN'),async(req,res)=>{const all=await complaints.find(scope(req.user)).toArray(),byCategory={},byLocation={};let hrs=0,n=0,rs=0,rn=0;all.forEach(c=>{byCategory[c.category]=(byCategory[c.category]||0)+1;byLocation[c.location]=(byLocation[c.location]||0)+1;if(c.resolvedAt){hrs+=(new Date(c.resolvedAt)-new Date(c.createdAt))/3600000;n++}if(c.rating){rs+=c.rating;rn++}});res.json({total:all.length,averageResolutionHours:n?Math.round(hrs/n*10)/10:0,averageRating:rn?Math.round(rs/rn*10)/10:0,byCategory,byLocation})});
app.post('/api/admin/staff',auth,role('ADMIN'),async(req,res)=>{const email=mail(req.body.email),password=String(req.body.password||'');if(!email||password.length<8||!req.body.name)return res.status(400).json({message:'Name, email and password required'});if(await users.findOne({email}))return res.status(409).json({message:'Email exists'});const u={name:req.body.name,email,passwordHash:pw(password),role:'STAFF',department:req.body.department||'General Services',schoolName:req.user.schoolName||req.body.schoolName||'',campusName:req.user.campusName||req.body.campusName||'',createdAt:new Date()};const r=await users.insertOne(u);u._id=r.insertedId;res.status(201).json(safe(u))});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));

async function start(){await client.connect();db=client.db(process.env.MONGODB_DB||'smart_campus');users=db.collection('users');sessions=db.collection('sessions');complaints=db.collection('complaints');counters=db.collection('counters');await Promise.all([users.createIndex({email:1},{unique:true}),sessions.createIndex({expiresAt:1},{expireAfterSeconds:0}),complaints.createIndex({id:1},{unique:true})]);if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD&&!await users.findOne({email:mail(process.env.ADMIN_EMAIL)}))await users.insertOne({name:process.env.ADMIN_NAME||'Campus Administrator',email:mail(process.env.ADMIN_EMAIL),passwordHash:pw(process.env.ADMIN_PASSWORD),role:'ADMIN',department:'Administration',schoolName:process.env.ADMIN_SCHOOL||'',campusName:process.env.ADMIN_CAMPUS||'',createdAt:new Date()});app.listen(port,()=>console.log('Smart Campus running on '+port+' with MongoDB'))}
start().catch(e=>{console.error(e);process.exit(1)});