import React,{useState}from'react';
import{clean,formatDate,isOverdue,slaText}from'./api';

export function Link({to,go,className='',children}){return <a href={to} className={className} onClick={e=>{if(!e.ctrlKey&&!e.metaKey&&!e.shiftKey){e.preventDefault();go(to)}}}>{children}</a>}

export function Header({go,path,user,logout,notifications=[],refreshNotifications}){const[menu,setMenu]=useState(false);const[bell,setBell]=useState(false);const unread=notifications.filter(n=>!n.readFlag).length;const nav=[['/services','Services'],['/report','Report'],['/track','Track'],['/updates','Updates'],...(user?.role==='STUDENT'?[['/map','Map']]:[]),['/help','Help']];return <header className="topbar"><div className="container topbar-inner"><Link to="/" go={go} className="brand-lockup"><img src="/logo-full.svg" alt="Smart Campus"/></Link><button className="mobile-toggle" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}>☰</button><nav className={menu?'main-nav open':'main-nav'}>{nav.map(([t,l])=><Link key={t} to={t} go={go} className={path===t?'active':''}>{l}</Link>)}</nav><div className="nav-actions">{user&&<div className="bell-wrap"><button className="bell" aria-label="Notifications" onClick={async()=>{setBell(!bell);await refreshNotifications?.()}}>●{unread>0&&<span>{unread}</span>}</button>{bell&&<div className="notification-pop"><strong>Notifications</strong>{notifications.length?notifications.slice(0,6).map(n=><button key={n.id} onClick={()=>{if(n.complaintId)go(`/complaint/${n.complaintId}`);setBell(false)}}><span>{n.message}</span><small>{formatDate(n.createdAt)}</small></button>):<p>No notifications yet.</p>}</div>}</div>}{user?<><Link to={user.role==='STUDENT'?'/portal':user.role==='ADMIN'?'/admin':'/staff'} go={go} className="text-link">{user.role==='STUDENT'?'Student portal':user.role==='ADMIN'?'Admin':'Operations'}</Link><button className="text-button" onClick={logout}>Sign out</button></>:<Link to="/login" go={go} className="text-link">Sign in</Link>}<Link to="/report" go={go} className="button primary compact">Report issue</Link></div></div></header>}

export function Footer({go}){return <footer><div className="container footer-grid"><div><img src="/logo-full.svg" alt="Smart Campus"/><p>Campus service and complaint management built for students, staff and administrators.</p></div><div><strong>Product</strong><button onClick={()=>go('/services')}>Services</button><button onClick={()=>go('/report')}>Report issue</button><button onClick={()=>go('/track')}>Track complaint</button></div><div><strong>Portals</strong><button onClick={()=>go('/portal')}>Student portal</button><button onClick={()=>go('/staff')}>Staff console</button><button onClick={()=>go('/admin')}>Admin analytics</button></div></div><div className="container footer-bottom">© 2026 Smart Campus Service & Complaint Management System · Giwa Abayomi</div></footer>}

export function Page({tag,title,text,children}){return <section className="page-section"><div className="container"><div className="page-head"><span>{tag}</span><h1>{title}</h1><p>{text}</p></div>{children}</div></section>}
export function Title({tag,title,text}){return <div className="section-title"><span>{tag}</span><h2>{title}</h2><p>{text}</p></div>}
export function Status({status}){return <span className={`status status-${String(status||'SUBMITTED').toLowerCase()}`}>{clean(status||'SUBMITTED')}</span>}
export function CaseRow({c,go}){return <button className="case-row" onClick={()=>go(`/complaint/${c.id}`)}><span className="case-id">#{c.id}</span><span className="case-main"><strong>{c.title}</strong><small>{c.location} · {clean(c.category)}</small></span><span className="case-sla"><em className={isOverdue(c)?'overdue-text':''}>{slaText(c)}</em><Status status={c.status}/></span></button>}
export function Empty({title,text}){return <div className="empty-state"><strong>{title}</strong><p>{text}</p></div>}
export function Detail({label,value}){return <div className="detail"><span>{label}</span><strong>{value||'—'}</strong></div>}
export function MetricLine({label,value}){return <div className="metric-line"><span>{label}</span><strong>{value}</strong></div>}
export function Quick({title,text,action,onClick}){return <button className="quick-card" onClick={onClick}><strong>{title}</strong><span>{text}</span><b>{action} →</b></button>}
export function StepMini({n,text}){return <div className="step-mini"><span>{n}</span><p>{text}</p></div>}
export function Feature({n,title,text}){return <div className="feature"><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>}
export function AnalyticsCard({label,value}){return <div className="analytics-card"><span>{label}</span><strong>{value}</strong></div>}
export function Bar({label,value,max}){return <div className="bar-row"><div><span>{label}</span><strong>{value}</strong></div><div className="bar-track"><span style={{width:`${Math.max(4,value/Math.max(max,1)*100)}%`}}></span></div></div>}
export function FAQ({q,a}){const[o,setO]=useState(false);return <article className="faq"><button onClick={()=>setO(!o)}><strong>{q}</strong><span>{o?'−':'+'}</span></button>{o&&<p>{a}</p>}</article>}
export function SkeletonRows(){return <div className="skeleton-rows">{[1,2,3].map(x=><div key={x}></div>)}</div>}
export function NotFound({go}){return <Page tag="404" title="Page not found" text="The page you requested does not exist or has moved."><button className="button primary" onClick={()=>go('/')}>Return home</button></Page>}
